<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\assets\DeepFry.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DeepFry.Protocol/DeepFry.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\assets\DeepFry.ico">
      <Link>DeepFry.ico</Link>
    </Resource>
    <Resource Include="..\favicon.png">
      <Link>favicon.png</Link>
    </Resource>
  </ItemGroup>

</Project>
