<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../DeepFry.Client/DeepFry.Client.csproj" />
    <ProjectReference Include="../../DeepFry.Host/DeepFry.Host.csproj" />
    <ProjectReference Include="../../DeepFry.Protocol/DeepFry.Protocol.csproj" />
  </ItemGroup>

</Project>
